---
apiVersion: v1
kind: Service
metadata:
  name: rustdesk-hbbs
  namespace: rustdesk
spec:
  selector:
    app: rustdesk
    component: hbbs
  type: NodePort
  ports:
    - name: tcp-21115
      port: 21115
      targetPort: 21115
      protocol: TCP
      nodePort: 32115
    - name: tcp-21116
      port: 21116
      targetPort: 21116
      protocol: TCP
      nodePort: 32116
    - name: udp-21116
      port: 21116
      targetPort: 21116
      protocol: UDP
      nodePort: 32116
    - name: tcp-21118
      port: 21118
      targetPort: 21118
      protocol: TCP
      nodePort: 32118
---
apiVersion: v1
kind: Service
metadata:
  name: rustdesk-hbbr
  namespace: rustdesk
spec:
  selector:
    app: rustdesk
    component: hbbr
  type: NodePort
  ports:
    - name: tcp-21117
      port: 21117
      targetPort: 21117
      protocol: TCP
      nodePort: 32117
    - name: tcp-21119
      port: 21119
      targetPort: 21119
      protocol: TCP
      nodePort: 32119
